# Generated by Django 3.2.16 on 2022-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection_app', '0002_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
