# Generated by Django 3.2.16 on 2022-10-30 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_collection_app', '0003_profilemodel_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
